name: Trigger auto deployment for pperpnext

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/pperpnext-AutoDeployTrigger-7f22b289-9003-441d-94f3-ed32f234bdd3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PPERPNEXT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PPERPNEXT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PPERPNEXT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.PPERPNEXT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PPERPNEXT_REGISTRY_PASSWORD }}
          containerAppName: pperpnext
          resourceGroup: PixelPacific
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


